'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PeriodicTable.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _As() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("As", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _In() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("In", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ac() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ac", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Al() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Al", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Am() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Am", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ArrowLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArrowLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ArrowRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArrowRight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ArrowUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArrowUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property At() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("At", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Au() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Au", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property B() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("B", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ba() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ba", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Be() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Be", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Bi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Bk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Br() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Br", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property C() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ca() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ca", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ce() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ce", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property closeImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("closeImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Co() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Co", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Dy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property eml2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eml2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Er() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Er", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Es() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Es", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Eu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Eu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ga() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ga", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Gd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property H() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("H", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property He() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("He", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Hf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Hg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ho() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ho", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property I() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("I", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ir() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ir", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property K() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("K", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Kr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property La() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("La", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Lead() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lead", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Li() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Li", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Lr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Lu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Md() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Md", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Mg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Mn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Mo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property N() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("N", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Na() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Na", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Nb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Nd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ne() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ne", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ni() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ni", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property No() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("No", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Np() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Np", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property O() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("O", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Os() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Os", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property P() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("P", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Po() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Po", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Rb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Re() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Re", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Rh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Rn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ru() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ru", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property S() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("S", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Se() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Se", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Si() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Si", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SoundOff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SoundOff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SoundOn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SoundOn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SoundOn1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SoundOn1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Te() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Te", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Th() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Th", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property theme3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("theme3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ti() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ti", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property U() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("U", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property V() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("V", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property W() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("W", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Xe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Xe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Yb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Yb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Zn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Zn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Zr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Zr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
